kind: pipeline
name: test

steps:
- name: practice
  image: alpine
  environment:
    USERNAME:
      from_secret: docker_username
  commands:
    - echo "You can call the secrets like this examples below."
    - echo $USERNAME
