---
kind: pipeline
type: docker
name: default

steps:
  - name: backend
    image: golang
    commands:
      - go build
      - go test
    # when:
    #   branch:
    #     - main

  # - name: frontend
  #   image: node
  #   commands:
  #     - npm install
  #     - npm test
    # when:
    #   branch:
    #     - main

  # - name: publish
  #   image: plugins/docker
  #   settings:
  #     repo: whchi/drone-example
  #     registry: index.docker.io

  - name: try
    image: busybox
    commands:
      - cat README.md